name: Publish Docker image and deploy
on:
  release:
    types: [published]
  push:
    branches: [issue-50]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Authenticate with GitHub package registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
      - name: npm install
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: npm build
        run: npm run build
      - uses: actions/upload-artifact@main
        with:
          name: artifacts
          path: dist/

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      stargate:
        image: stargateio/stargate-3_11:v1.0.13
        ports:
          - 8080:8080
          - 8081:8081
          - 8082:8082
        env:
          CLUSTER_NAME: stargate
          CLUSTER_VERSION: 3.11
          DEVELOPER_MODE: true
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Authenticate with GitHub package registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/download-artifact@main
        with:
          name: artifacts
          path: dist
      - name: npm install
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: test
        run: npm test

  push_to_registry:
    name: Push Docker image to GitHub Packages
    needs: test
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v2
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: version dockerfile
        run: sed -i 's/v0.0.0/v${{ steps.package-version.outputs.current-version}}/g' Dockerfile
      - name: set up Docker builder
        uses: docker/setup-buildx-action@v1
      - name: log into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: push to Github Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: 'github_token=${{ secrets.GITHUB_TOKEN }}'
          # secrets: |
          #   "github_token=${{ secrets.GITHUB_TOKEN }}"
          tags: |
            ghcr.io/eddiehubcommunity/api:v${{ steps.package-version.outputs.current-version}}
            ghcr.io/eddiehubcommunity/api:latest
